version: "2"

services:
  nginx:
    image: nginx:1.15.2-alpine
    container_name: my-static-files
    mem_limit: 10m
    expose:
      - 80
    ports:
      - 8888:80
    volumes:
      - ./www:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - traefik.enable=false

  puller:
    image: wzulfikar/go-puller
    mem_limit: 10m
    volumes:
      - ./:/repo
    ports:
      - 9999:9999
